### ISSUE TITLE
cascadenik-style.py is broken in 1.0.0 release

### ISSUE THREAD

**Issue by springmeyer** [mapnik/Cascadenik#10]
A user reported this to me by email. Traveling right now, but if nobody grabs this I can get to it on monday.

<code>

$ ./cascadenik-style.py example.mss 
Traceback (most recent call last):
  File "./cascadenik-style.py", line 49, in <module>
    sys.exit(main(stylefile))
  File "./cascadenik-style.py", line 17, in main
    declarations = cascadenik.stylesheet_declarations(input,is_gym=True)
TypeError: stylesheet_declarations() got an unexpected keyword argument 'is_gym'
</code>

**Comment by migurski** [comment]
I'll have a look at this later today.

**Comment by migurski** [comment]
Replaced old is_gym argument to stylesheet_declarations() with new is_merc parameter. Bumped to 1.0.2, closed by 0f789b1ddebb27acf73f195bc7c7300ca30e8a3f.
