### ISSUE TITLE
Problem with line-dasharray

### ISSUE THREAD

**Issue by plepe** [mapnik/Cascadenik#11]
When I try to compile a style with a line-dasharray with more than two elements, I get the following message:

<pre>
Traceback (most recent call last):
  File "/usr/local/bin/cascadenik-compile.py", line 92, in <module>
    sys.exit(main(layersfile, outputfile, **options.__dict__))
  File "/usr/local/bin/cascadenik-compile.py", line 33, in main
    cascadenik.load_map(mmap, src_file, dirname(realpath(dest_file)), **load_kwargs)
  File "/usr/local/lib/python2.6/dist-packages/cascadenik/__init__.py", line 65, in load_map
    compile(src_file, dirs, verbose, datasources_cfg=datasources_cfg).to_mapnik(map, dirs)
  File "/usr/local/lib/python2.6/dist-packages/cascadenik/output.py", line 54, in to_mapnik
    sym = symbolizer.to_mapnik()
  File "/usr/local/lib/python2.6/dist-packages/cascadenik/output.py", line 230, in to_mapnik
    stroke.add_dash(*self.dashes.values)
Boost.Python.ArgumentError: Python argument types in
    Stroke.add_dash(Stroke, int, int, int, int)
did not match C++ signature:
    add_dash(mapnik::stroke {lvalue}, float length, float gap)
</pre>

The problematic rule looks like this:

<pre>
.admin[admin_level=6][zoom>=14] {
  line-dasharray: 2,2,4,4;
  line-width: 3;
}
</pre>

If I change the line-dasharray to

<pre>
    line-dasharray: 2,2;
</pre>

the compilation works.

I'm using the newest version (commit d607ac00a352aad574d62160ec8460292fd2e348) from Github.

Please fix!

**Comment by springmeyer** [comment]
k, will take some looking into that I don't have time for atm, but thanks _very_ much for reporting. basically I'm not sure if this ever worked - but you are right that Cascadenik should be able to support the full expressiveness that Mapnik does for arrays

**Comment by plepe** [comment]
It definitely worked, I have an old version running on another system (SVN r768) and I'm using the same rules there. Thx for looking into it!

**Comment by migurski** [comment]
Fixed in fd8c79e, releasing as 2.0.1.
