### ISSUE TITLE
Supporting url based resources that use a query string

### ISSUE THREAD

**Issue by springmeyer** [mapnik/Cascadenik#14]
Our current use of HTTPConnection discards the query string, so things like

```
http://geocommons.com/overlays/78664/features.json?geojson=1
```

do not work as per http://developer.geoiq.com/blog/2010/12/08/integrating-geocommons-datasets-with-polymaps/

**Comment by springmeyer** [comment]
https://github.com/mapnik/Cascadenik/commit/a55a26b2c2b376541248410df4f7fe8d529e5d02

and

https://github.com/mapnik/Cascadenik/commit/d59645a65f175638956df32e039781750bbbb6d2

**Comment by migurski** [comment]
Yikes, that's an oversight on my part. I'll fix ASAP, might be a few days.

**Comment by springmeyer** [comment]
Mike, note I already fixed it in https://github.com/mapnik/Cascadenik/commit/a55a26b2c2b376541248410df4f7fe8d529e5d02
