### ISSUE TITLE
Revisit XML bad/good

### ISSUE THREAD

**Issue by springmeyer** [mapnik/Cascadenik#23]
Has the move to using the Mapnik python bindings (over direct XML authoring) been an overall good move for the project? I admit that it has felt like a mistake at the times when lacking features in the Mapnik python bindings have slowed things down. While the biggest blocker, `FontSets`, are now [fixed](https://github.com/mapnik/mapnik/issues/348), the other big reason I pushed for the move was performance, and that is now radically improved for XML loading: http://mapnik.org/news/2012/04/06/faster-map-loading/. And these XML loading improvements are not going directly benefit the map construction speeds via python.

So I would be interested in @migurski and @rcoup's perspective on this. Any reason we should consider moving back to XML from your perspective?

**Comment by migurski** [comment]
Yay for FontSets, I’ve been meaning to look at that soon since it’s come up with a few client projects. I intend to implement it just like Carto and CSS do, with a list of font face names as strings.

I think it’s still a good move in the sense that we have a direct `load_map()` function in Cascadenik that gives you back a usable Mapnik instance. I also like letting Mapnik generate its own XML. I don’t like that you have to recompile to XML on every system where you’re deploying a map, but that’ll remain necessary as long as we’re monkeying with paths so it’s not a big deal.

**Comment by springmeyer** [comment]
Okay, thanks for the thoughts! So, it sounds like sticking with the python approach will work fine. I'll just say then that when performance with large stylesheets needs to improve, then the first place to look will be at modifying how mapnik.Filter/Expressions are created. Eg. when you do in python `mapnik.Expression(<some string>)`, about half the time to parse that string is taken up in creating the instance of the parser (internally) and half in actually parsing the string. We could expose in Mapnik's python bindings some way to create a parser once and then reuse it, but we're unlikely to do this unless it is needed by Cascadenik. It would look something like:

``` python
parser = mapnik.ExpressionFactory()
filter = parser.parse("[name] = 'foo'")
```

**Comment by migurski** [comment]
What kinds of speedups are you actually talking about?

**Comment by migurski** [comment]
Which is to say, on the order of a few msec per construction? If there are obvious wins here and I’m doing something really dumb then I’ll adapt to whatever you say.

**Comment by nvkelso** [comment]
Looks to be 50% faster:
http://mapnik.org/news/2012/04/06/faster-map-loading/

**Comment by rcoup** [comment]
Feels like it's good for mapnik to have healthy bindings in a dynamic
language - we load XML files and mess with them dynamically sometimes,
build maps entirely via python other times, and use cascadenik as well :)

Whether its good for cascadenik is another question again. I'd say yes.
@migurski's the guru though

**Comment by springmeyer** [comment]
cool, okay, going to close then - sounds like python is working out. As far as keeping python map construction speeds on par with optimizations in the direct XML loading, that will not be important until you want to speed up the parsing of large stylesheets. If they have lots of Filters in Rules then performance should double. I've created a separate issue to track this idea: https://github.com/mapnik/mapnik/issues/1244.
