### ISSUE TITLE
text-max-char-angle-delta doesn't output max_char_angle_delta

### ISSUE THREAD

**Issue by ejsarge** [mapnik/Cascadenik#25]
Targetting mapnik 0.7.1

mss

```
#course-trail-label trail_name
{
    text-spacing: 256;
    text-placement: line;
    text-max-char-angle-delta: 37;

    text-face-name: 'PT Sans Narrow Regular';
    text-fill: #5a3b00;
    text-size: 8;

    text-halo-fill: #f7f7e6;
    text-halo-radius: 1;

    text-dy: 10;
}
```

Actual resulting xml snippet:

```
   <Rule name="rule 4">
      <TextSymbolizer dy="10" face_name="PT Sans Narrow Regular" fill="rgb(90,59,0)" halo_fill="rgb(247,247,230)" halo_radius="1" name="trail_name" placement="line" size="8" spacing="256" />
    </Rule>'
```

Expected resulting xml snippet:

```
<Rule name="rule 4">
    <TextSymbolizer dy="10" face_name="PT Sans Narrow Regular" fill="rgb(90,59,0)" halo_fill="rgb(247,247,230)" halo_radius="1" name="trail_name" placement="line" size="8" spacing="256" max_char_angle_delta="37"/>
</Rule>'
```

**Comment by mojodna** [comment]
Can reproduce with cascadenik-2.6.4 and mapnik-0.7.0-2ubuntu1 on Ubuntu 10.04.

**Comment by mojodna** [comment]
This was fixed in mapnik 0.7.2 (mapnik/mapnik@80aab72438a12479532077af3e4ef3904929f98d).

**Comment by mojodna** [comment]
FWIW, I've packaged mapnik-0.7.3 for Ubuntu 10.04 (mapnik-0.7.3-1mojodna1~lucid1) and stuck it in a PPA here: https://launchpad.net/~mojodna/+archive/random

**Comment by springmeyer** [comment]
cool @mojodna. It's not at all obvious (I realize now) but https://launchpad.net/~mapnik/+archive/nightly-0.7/+packages also contains a build of the Mapnik 0.7.x branch which is basically == to the tagged 0.7.3.

**Comment by springmeyer** [comment]
heh, looking more closely now I see those builds actually failed, so nm!

**Comment by mojodna** [comment]
I saw those, but assumed that 0.7 support had gone the way of the dodo given the dates and failures, so ripped off the Debian packaging and updated it for 0.7.3.

**Comment by springmeyer** [comment]
cool, sounds good. yeah, 0.7.x is pretty ancient at this point. Hope you have a good reason for using it ;)

**Comment by mojodna** [comment]
Not yet, other than potential assumptions for a near-deadline project ;-)
